services:
  rpub:
    image: rpub/rpub:RPUB_MVN_VERSION
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bb", "-e", "(slurp \"http://localhost:3000\")"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    ports:
      - '3000:3000'
    volumes:
      - ./data:/app/data
      - ~/.m2:/root/.m2
      - ~/.gitlibs:/root/.gitlibs
